### ISSUE TITLE
mysql not deploying on focal

### ISSUE THREAD

**Issue by barrettj12** [canonical/mysql-operator#22]
### Bug Description

The `mysql` charm is not deploying on focal - it goes into an error state.
```
App          Version  Status   Scale  Charm  Channel  Rev  Exposed  Message
mysql-focal           blocked      1  mysql  edge      68  no       Failed to initialize MySQL users
```

### To Reproduce

```
juju deploy mysql --channel edge --series focal
```

### Environment

Running Juju locally, v3.0-beta3 (SHA fcf07484)
OS: Ubuntu 20.04 LTS
on cloud LXD v5.3-91e042b
using mysql channel latest/edge, series focal

### Relevant log output

```shell
unit-mysql-focal-0: 10:15:16 INFO juju.worker.uniter.operation ran "install" hook (via hook dispatching script: dispatch)
unit-mysql-focal-0: 10:15:16 INFO juju.worker.uniter.operation ran "database-peers-relation-created" hook (via hook dispatching script: dispatch)
unit-mysql-focal-0: 10:15:16 INFO juju.worker.uniter found queued "leader-elected" hook
unit-mysql-focal-0: 10:15:17 INFO juju.worker.uniter.operation ran "leader-elected" hook (via hook dispatching script: dispatch)
unit-mysql-focal-0: 10:15:17 INFO juju.worker.uniter.operation ran "config-changed" hook (via hook dispatching script: dispatch)
unit-mysql-focal-0: 10:15:17 INFO juju.worker.uniter found queued "start" hook
unit-mysql-focal-0: 10:15:18 INFO unit.mysql-focal/0.juju-log Running legacy hooks/start.
unit-mysql-focal-0: 10:15:18 ERROR unit.mysql-focal/0.juju-log Failed to configure users for: 10.67.163.47 with error b"ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/src/mysqlsh_helpers.py", line 201, in _run_mysqlcli_script
    return subprocess.check_output(command, stderr=subprocess.PIPE).decode("utf-8")
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mysql', '-u', 'root', '--protocol=SOCKET', '--socket=/var/run/mysqld/mysqld.sock', '-e', "CREATE USER 'root'@'%' IDENTIFIED BY 'dlXzZ3UxMLEbtTAlk6ge8xFv'; GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION"]' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/lib/charms/mysql/v0/mysql.py", line 258, in configure_mysql_users
    self._run_mysqlcli_script("; ".join(create_root_user_commands))
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/src/mysqlsh_helpers.py", line 203, in _run_mysqlcli_script
    raise MySQLClientError(e.stderr)
charms.mysql.v0.mysql.MySQLClientError: b"ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n"
unit-mysql-focal-0: 10:15:19 INFO juju.worker.uniter.operation ran "start" hook (via hook dispatching script: dispatch)
unit-mysql-focal-0: 10:15:19 INFO juju.worker.uniter.operation ran "database-peers-relation-changed" hook (via hook dispatching script: dispatch)
unit-mysql-focal-0: 10:15:15 ERROR unit.mysql-focal/0.juju-log Failed to install apt packages
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/src/mysqlsh_helpers.py", line 113, in install_and_configure_mysql_dependencies
    apt.add_package(MYSQL_APT_PACKAGE_NAME)
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 758, in add_package
    pkg, success = _add(p, version, arch)
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 799, in _add
    pkg.ensure(state=PackageState.Present)
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 289, in ensure
    self._add()
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 261, in _add
    self._apt(
  File "/var/lib/juju/agents/unit-mysql-focal-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 255, in _apt
    raise PackageError(
charms.operator_libs_linux.v0.apt.PackageError: Could not install package(s) [['mysql-server-8.0=8.0.29-0ubuntu0.20.04.3']]: None
unit-mysql-focal-0: 10:17:49 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
```

**Comment by jnsgruk** [comment]
I think we'll struggle with the forced series deploy all the time we're not using snaps - it looks like we're pinning to specific versions of MySQL, which will obviously vary across Ubuntu series'.
