### ISSUE TITLE
"storage detaching" hook fails

### ISSUE THREAD

**Issue by barrettj12** [canonical/mysql-operator#23]
### Bug Description

When trying to remove mysql (revision cs:67), it ends up with status "error" and message `hook failed: "storage-detaching"`.

### To Reproduce

```
juju add-model m
juju deploy cs:mysql-67
juju destroy-model -y m
```

### Environment

Running Juju locally, v3.0-beta3 (SHA fcf07484)
OS: Ubuntu 20.04 LTS
on cloud LXD v5.3-91e042b
using mysql revision 67 (channel candidate)

### Relevant log output

```shell
unit-mysql-0: 11:57:21 ERROR juju.worker.uniter.operation hook "database-storage-detaching" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-0: 11:57:21 INFO juju.worker.uniter awaiting error resolution for "storage-detaching" hook
unit-mysql-0: 11:58:01 INFO juju.worker.uniter awaiting error resolution for "storage-detaching" hook
unit-mysql-0: 11:58:02 ERROR unit.mysql/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 279, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 199, in _on_database_storage_detaching
    self._mysql.remove_instance(unit_label)
  File "./src/charm.py", line 253, in _mysql
    peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/model.py", line 539, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-0: 11:58:02 ERROR juju.worker.uniter.operation hook "database-storage-detaching" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-0: 11:58:02 INFO juju.worker.uniter awaiting error resolution for "storage-detaching" hook
unit-mysql-0: 11:59:25 INFO juju.worker.uniter awaiting error resolution for "storage-detaching" hook
unit-mysql-0: 11:59:25 ERROR unit.mysql/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 279, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 199, in _on_database_storage_detaching
    self._mysql.remove_instance(unit_label)
  File "./src/charm.py", line 253, in _mysql
    peer_data["cluster-name"],
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/ops/model.py", line 539, in __getitem__
    return self._data[key]
KeyError: 'cluster-name'
unit-mysql-0: 11:59:25 ERROR juju.worker.uniter.operation hook "database-storage-detaching" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-0: 11:59:25 INFO juju.worker.uniter awaiting error resolution for "storage-detaching" hook
unit-mysql-0: 11:59:58 INFO juju.worker.uniter awaiting error resolution for "storage-detaching" hook
```

**Comment by shayancanonical** [comment]
@barrettj12 We just merged a fix. Issue should be resolved
